### ISSUE TITLE
about generation texts code

### ISSUE THREAD

**Issue by wenyijiang** [hiaoxui/D2T-Grounding#1]
Hi！
    Thanks for your excellent job! 
    I have read your paper！I want to know is there any code about generation texts. I just find about the tag part in your code.Thanks a lot !

**Comment by hiaoxui** [comment]
I replied to Wenyi via email so I close the issue.

**Comment by ZiweiHe** [comment]
Hi, can I also have the code for text generation? Thank you!!

**Comment by ZiweiHe** [comment]
My email: ziweihe@outlook.com 
:)
